spring:
  datasource:
    url: jdbc:h2:mem:Cadastro
    username: user
  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
