spring:
  datasource:
    url: jdbc:h2:mem:Cadastro
    username: user
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql_db:3307/Cadastro?useTimezone=true&serverTimezone=UTC
#    username: root
#    password: C@Da$tr01_rootpassword
  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

cors:
  originPatterns: http://localhost:8080,http://localhost:8080/h2-console,http://localhost:4200
security:
  jwt:
    token:
      secret-key: 53cr37
      expired-length: 180000